### ISSUE TITLE
[Feature]: Friendly to gradio_client remote access

### ISSUE THREAD

**Issue by c2j** [binary-husky/gpt_academic#1083]
### Class | 类型

程序主体

### Feature Request | 功能请求

I want to integrate get_academic backend with my chatbot, so I use gradio client to connect the server by api, I think fn_index is the internet call order, but it may change in future if the source code refactored, So I want to fix them.
```
>>>from gradio_client import Client
>>>client = Client("http://192.168.1.4:22387")
>>>client.view_api()
Client.predict() Usage Info
---------------------------
Named API endpoints: 0

Unnamed API endpoints: 42

 - predict(显示隐藏功能区, fn_index=0) -> (value_10, 输入区2, value_17, value_72, 高级参数输入区)
    Parameters:
     - [Checkboxgroup] 显示隐藏功能区: List[str] 
    Returns:
     - [Textbox] value_10: str 
     - [Textbox] 输入区2: str 
     - [Button] value_17: str 
     - [Button] value_72: str 
     - [Textbox] 高级参数输入区: str 

 - predict(local_llm_maxlength, 更换llm模型请求源, parameter_10, 输入区2, topp_nucleus_sampling, temperature, 当前模型gpt35turbo, system_prompt, 高级参数输入区, fn_index=1) -> (当前模型gpt35turbo, value_19)
    Parameters:
     - [Slider] local_llm_maxlength: int | float (numeric value between 256 and 8192) 
     - [Dropdown] 更换llm模型请求源: str (Option from: ['gpt-3.5-turbo-16k', 'gpt-3.5-turbo', 'azure-gpt-3.5', 'api2d-gpt-3.5-turbo', 'gpt-4', 'api2d-gpt-4', 'chatglm', 'moss', 'newbing', 'stack-claude']) 
     - [Textbox] parameter_10: str 
     - [Textbox] 输入区2: str 
     - [Slider] topp_nucleus_sampling: int | float (numeric value between 0 and 1.0) 
     - [Slider] temperature: int | float (numeric value between 0 and 2.0) 
     - [Chatbot] 当前模型gpt35turbo: str (filepath to JSON file) 
     - [Textbox] system_prompt: str 
     - [Textbox] 高级参数输入区: str 
    Returns:
     - [Chatbot] 当前模型gpt35turbo: str (filepath to JSON file) 
     - [Markdown] value_19: str 
...
```
