### ISSUE TITLE
[Feature]: hf社区主题可以使用本地代码高亮吗？

### ISSUE THREAD

**Issue by oreeke** [binary-husky/gpt_academic#1695]
### Class | 类型

程序主体

### Feature Request | 功能请求

现在好像只有已经本地化的主题支持代码高亮。

**Comment by oreeke** [comment]
@binary-husky 我直接把default.css扔到gradio.py，`--background-fill-primary: #050810;`注释掉，就可以用社区主题了，这样沿用了本地default处理markdown或highlight的独特样式，大部分样式还是社区原样。

- gradio.py
 
```py
with open(os.path.join(theme_dir, "common.css"), "r", encoding="utf-8") as f:
    advanced_css = f.read()
with open(os.path.join(theme_dir, "default.css"), "r", encoding="utf-8") as f:
    advanced_css += f.read()
```

- default.css

```css
.dark {
    /* --background-fill-primary: #050810; */
    --body-background-fill: var(--background-fill-primary);
}
```

![屏幕截图 2024-04-10 211704](https://github.com/binary-husky/gpt_academic/assets/22180904/b1074b52-bcc0-4801-bce8-8fa469e02754)

但这只是简单粗暴的方法，实际需要对本地和远程样式进行筛选才能完美，暂时没想到好办法。
另外还有个问题，更换社区主题后本地不记录日志了，没找到具体原因，日志的记录会受主题影响吗？
