### ISSUE TITLE
使用宝塔Docker-compose，5分钟内在海外服务器上搭建gpt_academic

### ISSUE THREAD

**Issue by daniellauyu** [binary-husky/gpt_academic#867]
- 在项目中复制`docker-compose.yml`文件内容，我这里复制的是方案一，因为我仅运行ChatGPT。将`USE_PROXY`设置为`False`，然后把原文件中的`proxies`整行直接删除。

```yml
version: '3'
services:
  gpt_academic_nolocalllms:
    image: ghcr.io/binary-husky/gpt_academic_nolocal:master
    environment:
      # 请查阅 `config.py` 以查看所有的配置信息
      API_KEY: 'sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
      USE_PROXY: 'False'
      LLM_MODEL: 'gpt-3.5-turbo'
      AVAIL_LLM_MODELS: '["gpt-3.5-turbo", "api2d-gpt-3.5-turbo", "gpt-4", "api2d-gpt-4", "newbing"]'
      WEB_PORT: '22303'
      ADD_WAIFU: 'True'

    # 与宿主的网络融合
    network_mode: "host"

    # 不使用代理网络拉取最新代码
    command: >
      bash -c "python3 -u main.py"
```

- 在宝塔Docker>Compose模板中添加模板，找到刚刚编辑好的模板，直接添加。

![image-20230613101312454-2](https://github.com/binary-husky/gpt_academic/assets/17739321/1b5923df-23c1-42b3-91e0-d34b7f6301fb)

- 然后在Docker>Compose中添加Compose项目，因为是海外服务器，所以速度也非常快，1分钟不到就添加成功了。

![image-20230613101451597-2](https://github.com/binary-husky/gpt_academic/assets/17739321/4713b067-8f4d-4e7d-ba25-1465593d7266)

- 分别在云服务器的安全组与宝塔的安全中放行端口，我上面用的是22303。

![image-20230613143223265-2](https://github.com/binary-husky/gpt_academic/assets/17739321/2198833c-e5e2-4224-8f4e-aab6b2e86928)

- 在网站中创建一个php静态站点，把域名解析到当前服务器。

![image-20230613143356661-2](https://github.com/binary-husky/gpt_academic/assets/17739321/791c6146-ec72-46a8-9350-cd04ab3b5476)

- 配置反向代理，在站点的设置中点击站点修改，找到反向代理，添加反向代理。

![image-20230613143533497-2](https://github.com/binary-husky/gpt_academic/assets/17739321/3177c9d1-fdbd-42f8-9620-7f1a9408bc9f)

- 添加完成之后，通过域名进行访问，即可拥有随时可访问的学术chatGPT。

![image-20230613143659103-2](https://github.com/binary-husky/gpt_academic/assets/17739321/970692a4-e5a2-4c14-9df6-0b20ed670eb9)

-  此时任何人都能访问这个，可以在`config.py`中添加账号，进入Docker>容器，找到目录，然后进入目录后找到`gpt`文件夹，找到文件夹中的`config.py`文件。

![image-20230613143958643-2](https://github.com/binary-husky/gpt_academic/assets/17739321/15e69f4b-46af-4c75-97b4-474a90f0b131)

- 将代码中的63行修改为你的用户名与密码，保存后重启下docker。在docker容器列表中点击重启即可。

```python
# [("username", "password"), ("username2", "password2"), ...]
AUTHENTICATION = [("username", "password")]
```

- 再次访问域名，即可出现登录页面。

![image-20230613144145481-2](https://github.com/binary-husky/gpt_academic/assets/17739321/a2b2aeb1-1495-4a13-9a25-73fd9767d89d)
