### ISSUE TITLE
[Feature]: 通过ChatGPT-to-API & ChatGPTProxy 的反向代理接入openai chatgpt

### ISSUE THREAD

**Issue by hongyi-zhao** [binary-husky/gpt_academic#900]
### Class | 类型

大语言模型

### Feature Request | 功能请求

有如下两个特性，非常不错：

1. Cloudflare bypass proxy 支持，比如下面这个：https://github.com/acheong08/ChatGPT-Proxy-V4
2. 基于1. 构建的反向代理，并利用[Access token](https://github.com/acheong08/ChatGPT#--access-token)访问，从而绕过[OpenAI API](https://openai.com/blog/openai-api)过期问题。

**Comment by binary-husky** [comment]
谢谢，不过鉴于目前api已经很便宜了，我不想再引入更多反向工程的东西了，因为反向工程的东西维护负担太重了……
欢迎讨论

**Comment by hongyi-zhao** [comment]
[V1.py](https://github.com/acheong08/ChatGPT/blob/main/src/revChatGPT/V1.py) 是基于(ChatGPT-Proxy-V4)[https://github.com/acheong08/ChatGPT-Proxy-V4]的具体的实现，或许可以作用一个插件来集成到gpt_academic中。

**Comment by acheong08** [comment]
There is no need to use ChatGPT-Proxy-V4 or add a dependency on revChatGPT.

To use ChatGPT for free, just swap the endpoint here:
https://github.com/binary-husky/gpt_academic/blob/59877dd728bc71b30099acd74c706a43e3cd770c/request_llm/bridge_all.py#L55

To one hosted via https://github.com/acheong08/ChatGPT-to-API/ which serves as a clone of the official API but via chat.openai.com.

A free endpoint to try out: https://free.churchless.tech/v1/chat/completions

**Comment by hongyi-zhao** [comment]
Nice, it does the trick.

**Comment by acheong08** [comment]
> Whether this method relies on the [access token](https://github.com/acheong08/ChatGPT#--access-token)?

yes

> Whether the [access token](https://github.com/acheong08/ChatGPT#--access-token) is obtained based on the API key?

No. Cycled through

**Comment by hongyi-zhao** [comment]
> No. Cycled through

Could you please describe the detailed steps?

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT-to-API/blob/master/internal/tokens/tokens.go

**Comment by hongyi-zhao** [comment]
> I upload a list of access tokens and it loops through them for each request. No API is used/accepted

This means that you must periodically check the expiration status of these access tokens and dynamically update them.

**Comment by acheong08** [comment]
I have a bash script running in a for loop to update every week. It's all automated.

**Comment by hongyi-zhao** [comment]
IMO, one access token needs one account, so you must have many accounts.

**Comment by acheong08** [comment]
> One access token needs one account, so you must have many accounts.

500 for public use and 500 for private use

**Comment by acheong08** [comment]
> If I use the free endpoint provided by you, aka, https://free.churchless.tech/v1/chat/completions, then no api-key of mine is needed. But based on my tries, if I don't set the API_KEY variable when using the above free endpoint with https://github.com/binary-husky/gpt_academic, it doesn't work at all, as shown below:

This is a front end thing. set randomly

**Comment by hongyi-zhao** [comment]
I still cannot understand what do you mean by saying that `set randomly`, more precisely, is it really necessary to set up this `API_KEY` when working via your free endpoint?

On the other hand, I also tried to call your `revChatGPT.V3` as follows:

This way works:
```shell
$ API_URL="https://free.churchless.tech/v1/chat/completions" python -m revChatGPT.V3 --api_key sk-xxx --truncate_limit $(( 16 * 1024 )) --model gpt-3.5-turbo-16k
```

This way fails:
```shell
$ API_URL="https://free.churchless.tech/v1/chat/completions" python -m revChatGPT.V3 --truncate_limit $(( 16 * 1024 )) --model gpt-3.5-turbo-16k
```

The error message is as follows:

```
V3.py: error: the following arguments are required: --api_key
```

**Comment by hongyi-zhao** [comment]
> I have a bash script running in a for loop to update every week. It's all automated.

Does this script call https://github.com/acheong08/OpenAIAuth under the hood?

> 500 for public use and 500 for private use

1. How to create so many accounts automatically?
2. What's the purpose of the 500 for private use?

**Comment by acheong08** [comment]
> On the other hand, I also tried to call your revChatGPT.V3 as follows:

V3 uses the official API. It is not relevant here

**Comment by acheong08** [comment]
> I still cannot understand what do you mean by saying that set randomly, more precisely, is it really necessary to set up this API_KEY when working via your free endpoint?

It is necessary to set an API key to use this specific repository. You can set something like `blahblahblah` and it would still work with the free endpoint

**Comment by acheong08** [comment]
>          How to create so many accounts automatically?

Browser automation with SMS verification from smspool

> What's the purpose of the 500 for private use?

Automation stuff. Closed source

**Comment by hongyi-zhao** [comment]
> V3 uses the official API. It is not relevant here

If so, why do you still read the environment variable as follows:

https://github.com/acheong08/ChatGPT/blob/a1c32f46c2409b5e880d0161c031f380b3957975/src/revChatGPT/V3.py#L290

`os.environ.get("API_URL") or "https://api.openai.com/v1/chat/completions",`

**Comment by hongyi-zhao** [comment]
> I upload a list of access tokens and it loops through them for each request. No API is used/accepted

This also means that each of these access tokens is precisely bound to one instance that provides the service, am I right?

**Comment by hongyi-zhao** [comment]
> Browser automation with SMS verification from smspool

Are there some free smspool providers for such purpose? BTW, I noticed [the following website](https://www.smspool.net/free-sms-verification), but not sure if it's truly free:

![image](https://github.com/binary-husky/gpt_academic/assets/11155854/ff29147d-b4f5-4c20-87c8-7802a67ed486)

**Comment by acheong08** [comment]
> If so, why do you still read the environment variable as follows:

V3 uses the official API. Some people require proxies

> This also means that each of these access tokens is precisely bound to one instance that provides the service, am I right?

Yes

> Are there some free smspool providers for such purpose? BTW, I noticed [the following website](https://www.smspool.net/free-sms-verification), but not sure if it's truly free:

None that works

**Comment by hongyi-zhao** [comment]
> > I still cannot understand what do you mean by saying that set randomly, more precisely, is it really necessary to set up this API_KEY when working via your free endpoint?
> 
> It is necessary to set an API key to use this specific repository. You can set something like `blahblahblah` and it would still work with the free endpoint

> > If so, why do you still read the environment variable as follows:
> 
> V3 uses the official API. Some people require proxies
> 
> >

Based on further tries, both `gpt_academic` and your `revChatGPT.V3` work with the following fake formal api_key when calling your free endpoint:

```shell
werner@X10DAi:~$ echo sk-$(tr -dc A-Za-z0-9 </dev/urandom | head -c 48)
sk-JF7HaOK6K01wTNxR6pjoH1VB2uT58xdrDMFn6xAdlioOGmET
```

**Comment by hongyi-zhao** [comment]
> None that works

Then, what's your solution?

**Comment by acheong08** [comment]
> > None that works
> 
> Then, what's your solution for such a tedious job?

I pay $0.1 per account for sms verification

**Comment by acheong08** [comment]
> So, I come to the following question: with a customized API_URL, can I tweak V3 to use [Email/Password](https://github.com/acheong08/ChatGPT#authentication-method-choose-1) based authentication, just as the one used by V1?

Yes. If you include access token as API key in request to ChatGPT-to-API, it will use your access token instead of the built in ones

**Comment by hongyi-zhao** [comment]
> I pay $0.1 per account for sms verification

What's your selected service provider?

**Comment by hongyi-zhao** [comment]
Another question: How to tweak your [revChatGPT.V1](https://github.com/acheong08/ChatGPT#v1-standard-chatgpt) work with an arbitrary fake formal api_key, when calling [your free endpoint](https://free.churchless.tech/v1/chat/completions)?

**Comment by binary-husky** [comment]
> 2\. https://free.churchless.tech

The program automatically detect api key.
Does it work if you simply try to use a random yet same-format api-key when using the free endpoint ?

**Comment by binary-husky** [comment]
> The program automatically detect api key.
> Does it work if you simply try to use a random yet same-format api-key when using the free endpoint ?

The program automatically detect api key.
Does it work if you simply try to use a random yet same-format api-key when using the free endpoint ?

**Comment by acheong08** [comment]
> Another question: How to tweak your [revChatGPT.V1](https://github.com/acheong08/ChatGPT#v1-standard-chatgpt) work without or with an arbitrary fake formal api_key, when calling [your free endpoint](https://free.churchless.tech/v1/chat/completions)?

V1 cannot call free endpoint

**Comment by acheong08** [comment]
> > I pay $0.1 per account for sms verification
> 
> What's your selected service provider?

smspool

**Comment by acheong08** [comment]
> > 2. https://free.churchless.tech
> 
> The program automatically detect api key. Does it work if you simply try to use a random yet same-format api-key when using the free endpoint ?

The current hosted free endpoint gives you 1 request per second using the keys already hosted in the back end. You can set an API key `sk-somethinghere` and that would just be ignored

**Comment by hongyi-zhao** [comment]
I've pointed out this here:

https://github.com/binary-husky/gpt_academic/issues/900#issuecomment-1619382193

**Comment by hongyi-zhao** [comment]
@acheong08 

> > > I pay $0.1 per account for sms verification
> > 
> > 
> > What's your selected service provider?
> 
> smspool

Do you mean [the following one](https://www.smspool.net/)?

![image](https://github.com/binary-husky/gpt_academic/assets/11155854/062f6023-806b-447f-9f7a-68cc206a0263)

**Comment by binary-husky** [comment]
Edit by binary husky:
For simplicity, add this line to config.py or config_private.py will work:

API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions":"https://free.churchless.tech/v1/chat/completions"}


![image](https://github.com/binary-husky/gpt_academic/assets/96192199/a006d4bd-cccf-4eab-b1c4-5a9937edabdc)

**Comment by hongyi-zhao** [comment]
Using a free endpoint provided by someone else is not what I'm advocating and initiating in this issue, and that endpoint could quickly become overwhelmed by the amount of access it receives. My goal is to build a free endpoint based on a tool like the [ChatGPT-to-API](https://github.com/acheong08/ChatGPT-to-API/blob/master/README_CN.md) provided by the author. Only such an approach is more worthy of consideration in terms of efficiency and stability.

**Comment by acheong08** [comment]
Replace the demo with your own endpoint. The endpoint provided is an instance of [ChatGPT-to-API](https://github.com/acheong08/ChatGPT-to-API/)

**Comment by binary-husky** [comment]
Sorry, I misunderstood the intention of this issue.

________________________________
发件人: Antonio Cheong ***@***.***>
发送时间: 2023年7月6日 09:17
收件人: binary-husky/gpt_academic ***@***.***>
抄送: binary-husky ***@***.***>; State change ***@***.***>
主题: Re: [binary-husky/gpt_academic] [Feature]: 通过免费的反向代理接入openai chatgpt (Issue #900)


Replace the demo with your own endpoint. The endpoint provided is an instance of ChatGPT-to-API<https://github.com/acheong08/ChatGPT-to-API/>

―

**Comment by binary-husky** [comment]
Sorry, I did not read this issue carefully and have previously misunderstood the intention of this issue.

Hope I'm not causing unnessary trouble, I apologize if there is any offense.

As remedy I will replace demo to fake url and write a document on how to use ChatGPT-to-API<https://github.com/acheong08/ChatGPT-to-API/>
________________________________
发件人: Antonio Cheong ***@***.***>
发送时间: 2023年7月6日 09:17
收件人: binary-husky/gpt_academic ***@***.***>
抄送: binary-husky ***@***.***>; State change ***@***.***>
主题: Re: [binary-husky/gpt_academic] [Feature]: 通过免费的反向代理接入openai chatgpt (Issue #900)


Replace the demo with your own endpoint. The endpoint provided is an instance of ChatGPT-to-API<https://github.com/acheong08/ChatGPT-to-API/>

―

**Comment by binary-husky** [comment]
@acheong08 hello, I'm trying to deploy ChatGPT-to-API
but I'm encountering 500 or 404, this is my docker-compose setting, is it correct? 
```
version: '3'

services:
  app:
    image: acheong08/chatgpt-to-api # 总是使用latest,更新时重新pull该tag镜像即可
    container_name: chatgpttoapi
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      ADMIN_PASSWORD: TotallySecurePassword
      PUID: user-DwkoYzRgkApoWn2Yxxxxxxxxx
      http_proxy: socks5h://localhost:11284
      Access_Token: eyJhbGciOiJSUzI1Nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

```

![image](https://github.com/binary-husky/gpt_academic/assets/96192199/b0906dd0-f316-47d5-869e-2a0d515773be)

**Comment by hongyi-zhao** [comment]
1. Do you really have a plus account?
2. Remove `PUID` and try again. 
3. The `PUID` is a cookie `_puid`.

See [here](https://github.com/acheong08/ChatGPT-to-API/issues/81) for more related discussions.

**Comment by binary-husky** [comment]
> 1. Do you really have a plus account?
> 2. Remove `PUID` and try again, see [here](https://github.com/acheong08/ChatGPT-to-API/issues/81#issuecomment-1623378147) for the related comment.
> 3. If you really want to use `PUID`, it should be obtained from your browser's cookie cache due that `PUID` is [a cookie `_puid`](https://github.com/acheong08/ChatGPT-to-API/issues/81#issuecomment-1623301063) and the description [here](https://github.com/acheong08/ChatGPT-to-API/blob/master/README_CN.md#%E8%8E%B7%E5%8F%96puid), as shown below, is wrong:
> 
> ![image](https://user-images.githubusercontent.com/11155854/251643763-b4b3a8da-3ba6-4ff4-8fc0-9e01caf923f9.png)

1. No, PUID=Plus_User_ID instead of Personal_User_ID?
2. what is the alternative if I do not have a plus (if I have plus and bind a credit card, I could have simply used APIs)?

**Comment by acheong08** [comment]
> No, PUID=Plus_User_ID instead of Personal_User_ID?

yes

> what is the alternative if I do not have a plus (if I have plus and bind a credit card, I could have simply used APIs)?

Plus not required. You just have to deal with rate limits. Alternative is proxies since it's IP based

**Comment by hongyi-zhao** [comment]
@binary-husky 
> 2\. what is the alternative if I do not have a plus (if I have plus and bind a credit card, I could have simply used APIs)?

I don't think so, due that OpenAI doesn't provide APIs even for plus accounts. Instead, the API access for the plus account is invited and managed by OpenAI, which doesn't ship with the plus account.

**Comment by hongyi-zhao** [comment]
@acheong08 
> Plus not required. You just have to deal with rate limits. Alternative is proxies since it's IP based

The key is to use a proxy pool managed by, say, [haproxy](https://github.com/haproxy/haproxy).

**Comment by hongyi-zhao** [comment]
@acheong08 

So, it seems that the following comment in the template [docker-compose.yml](https://github.com/acheong08/ChatGPT-to-API/blob/master/docker-compose.yml) is not so appropriate:

```yaml
      # If the parameter API_REVERSE_PROXY is empty, the default request URL is https://chat.openai.com/backend-api/conversation, and the PUID is required.
      # You can get your PUID for Plus account from the following link: https://chat.openai.com/api/auth/session.
      PUID: xxx
```

**Comment by binary-husky** [comment]
Still have some problem, without PUID, should I use Access Token? 

Should I pass `Access_Token`, `AccessToken` or `accessToken`?

Following configuration still return 500 error:
```
version: '3'

services:
  app:
    image: acheong08/chatgpt-to-api # 总是使用latest,更新时重新pull该tag镜像即可
    container_name: chatgpttoapi
    restart: unless-stopped
    ports:
      - '8080:8080'
      - '11284:11284'
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      ADMIN_PASSWORD: TotallySecurePassword
      http_proxy: socks5h://localhost:11284
      https_proxy: socks5h://localhost:11284
      Access_Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by hongyi-zhao** [comment]
As described [here](https://github.com/acheong08/ChatGPT-to-API/blob/master/README.md#authentication), the access token retrieval has been automated. So, I think you should instead use `OPENAI_EMAIL` and `OPENAI_PASSWORD`, as documented [here](https://github.com/acheong08/ChatGPT-to-API/blob/master/README.md#environment-variables).

**Comment by hongyi-zhao** [comment]
@acheong08 

Just for confirmation, is the following bypass endpoint built with [ChatGPTProxy](https://github.com/acheong08/ChatGPTProxy)?

https://github.com/acheong08/ChatGPT-to-API/blob/091f2b4851aba597a5f47e1d0532ad3cf071b32d/docker-compose.yml#L15     
`
API_REVERSE_PROXY: https://bypass.churchless.tech/api/conversation`

**Comment by binary-husky** [comment]
> @binary-husky As described [here](https://github.com/acheong08/ChatGPT-to-API/blob/master/README.md#authentication), the access token retrieval has been automated. So, I think you should instead use `OPENAI_EMAIL` and `OPENAI_PASSWORD`, as documented [here](https://github.com/acheong08/ChatGPT-to-API/blob/master/README.md#environment-variables).

still no luck, give me some bad errors this time

![image](https://github.com/binary-husky/gpt_academic/assets/96192199/2d824db6-94c1-4979-aaf0-c74bff6c43e2)

**Comment by hongyi-zhao** [comment]
The `docker-compose.yml`:

```yaml
version: '3'

services:
  app:
    image: acheong08/chatgpt-to-api # 总是使用latest,更新时重新pull该tag镜像即可
    container_name: chatgpttoapi
    restart: unless-stopped
    ports:
      - '18080:18080'
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 18080
      ADMIN_PASSWORD: TotallySecurePassword
      # The proxy running on host:
      http_proxy:  socks5h://192.168.1.8:18890
      https_proxy: socks5h://192.168.1.8:18890
      # Reverse Proxy - Available on accessToken
      #API_REVERSE_PROXY: https://bypass.churchless.tech/api/conversation
      # If the parameter API_REVERSE_PROXY is empty, the default request URL is https://chat.openai.com/backend-api/conversation, and the PUID is required.
      # You can get your PUID for Plus account from the following link: https://chat.openai.com/api/auth/session.
      #PUID: xxx
      OPENAI_EMAIL: "my-email"
      OPENAI_PASSWORD: "my-password"
```

The error:

```bash
werner@X10DAi:~/Public/repo/github.com/acheong08/ChatGPT-to-API.git$ go version
go version devel go1.21-39c5070712 Thu Jul 6 23:23:41 2023 +0000 linux/amd64
werner@X10DAi:~/Public/repo/github.com/acheong08/ChatGPT-to-API.git$ docker-compose up
Recreating chatgpttoapi ... done
Attaching to chatgpttoapi
chatgpttoapi | [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
chatgpttoapi | 
chatgpttoapi | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
chatgpttoapi |  - using env:	export GIN_MODE=release
chatgpttoapi |  - using code:	gin.SetMode(gin.ReleaseMode)
chatgpttoapi | 
chatgpttoapi | [GIN-debug] GET    /ping                     --> main.main.func1 (4 handlers)
chatgpttoapi | [GIN-debug] PATCH  /admin/password           --> main.passwordHandler (5 handlers)
chatgpttoapi | [GIN-debug] PATCH  /admin/tokens             --> main.tokensHandler (5 handlers)
chatgpttoapi | [GIN-debug] PATCH  /admin/puid               --> main.puidHandler (5 handlers)
chatgpttoapi | [GIN-debug] PATCH  /admin/openai             --> main.openaiHandler (5 handlers)
chatgpttoapi | [GIN-debug] OPTIONS /v1/chat/completions      --> main.optionsHandler (4 handlers)
chatgpttoapi | [GIN-debug] POST   /v1/chat/completions      --> main.nightmare (5 handlers)
chatgpttoapi | [GIN-debug] GET    /v1/engines               --> main.engines_handler (5 handlers)
chatgpttoapi | [GIN-debug] GET    /v1/models                --> main.engines_handler (5 handlers)
chatgpttoapi | 2023/07/07 14:36:23 1 0.0.0.0:18080
chatgpttoapi | panic: runtime error: invalid memory address or nil pointer dereference
chatgpttoapi | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8c13eb]
chatgpttoapi | 
chatgpttoapi | goroutine 129 [running]:
chatgpttoapi | github.com/acheong08/OpenAIAuth/auth.(*Authenticator).partOne(0xc000550000)
chatgpttoapi | 	/go/pkg/mod/github.com/acheong08/!open!a!i!auth@v0.0.0-20230609193408-55a0f33f1057/auth/OpenAiAuth.go:158 +0xb8b
chatgpttoapi | github.com/acheong08/OpenAIAuth/auth.(*Authenticator).Begin(...)
chatgpttoapi | 	/go/pkg/mod/github.com/acheong08/!open!a!i!auth@v0.0.0-20230609193408-55a0f33f1057/auth/OpenAiAuth.go:121
chatgpttoapi | main.init.0.func1()
chatgpttoapi | 	/app/main.go:30 +0xd3
chatgpttoapi | created by main.init.0
chatgpttoapi | 	/app/main.go:23 +0x71
```

I also tried to use the `API_REVERSE_PROXY` as follows in the `docker-compose.yml`:

```yaml
version: '3'

services:
  app:
    image: acheong08/chatgpt-to-api # 总是使用latest,更新时重新pull该tag镜像即可
    container_name: chatgpttoapi
    restart: unless-stopped
    ports:
      - '18080:18080'
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 18080
      ADMIN_PASSWORD: TotallySecurePassword
      http_proxy:  socks5h://192.168.1.8:18890
      https_proxy: socks5h://192.168.1.8:18890
      # Reverse Proxy - Available on accessToken
      API_REVERSE_PROXY: https://bypass.churchless.tech/api/conversation
      # If the parameter API_REVERSE_PROXY is empty, the default request URL is https://chat.openai.com/backend-api/conversation, and the PUID is required.
      # You can get your PUID for Plus account from the following link: https://chat.openai.com/api/auth/session.
      #PUID: xxx
      #OPENAI_EMAIL: "bgrandstaff9@ramons.site"
      #OPENAI_PASSWORD: "#2fV8GX4#D"
```

This time, the docker container can be started successfully:

```bash
werner@X10DAi:~/Public/repo/github.com/acheong08/ChatGPT-to-API.git$ docker-compose up
Recreating chatgpttoapi ... done
Attaching to chatgpttoapi
chatgpttoapi | [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
chatgpttoapi | 
chatgpttoapi | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
chatgpttoapi |  - using env:	export GIN_MODE=release
chatgpttoapi |  - using code:	gin.SetMode(gin.ReleaseMode)
chatgpttoapi | 
chatgpttoapi | [GIN-debug] GET    /ping                     --> main.main.func1 (4 handlers)
chatgpttoapi | [GIN-debug] PATCH  /admin/password           --> main.passwordHandler (5 handlers)
chatgpttoapi | [GIN-debug] PATCH  /admin/tokens             --> main.tokensHandler (5 handlers)
chatgpttoapi | [GIN-debug] PATCH  /admin/puid               --> main.puidHandler (5 handlers)
chatgpttoapi | [GIN-debug] PATCH  /admin/openai             --> main.openaiHandler (5 handlers)
chatgpttoapi | [GIN-debug] OPTIONS /v1/chat/completions      --> main.optionsHandler (4 handlers)
chatgpttoapi | [GIN-debug] POST   /v1/chat/completions      --> main.nightmare (5 handlers)
chatgpttoapi | [GIN-debug] GET    /v1/engines               --> main.engines_handler (5 handlers)
chatgpttoapi | [GIN-debug] GET    /v1/models                --> main.engines_handler (5 handlers)
chatgpttoapi | 2023/07/07 14:43:00 1 0.0.0.0:18080
```

But I still failed to use it with gpt_academic:

```shell
werner@X10DAi:~$ gpt_academic 
[ENV_VAR] 尝试加载proxies，默认值：None --> 修正值：{ "http": "socks5h://localhost:18890", "https": "socks5h://localhost:18890" }
 [ENV_VAR] 成功读取环境变量proxies 
 [PROXY] 网络代理状态：已配置。配置信息如下： {'http': 'socks5h://localhost:18890', 'https': 'socks5h://localhost:18890'} 
[ENV_VAR] 尝试加载API_KEY，默认值：sk-此处填API密钥 --> 修正值：sk-a8Tvun8J66ZOPdfqvmU2e2Uzw5JqPoYhVh6TCTjWQi0nTKdC
 [ENV_VAR] 成功读取环境变量API_KEY 
 [API_KEY] 本项目现已支持OpenAI和API2D的api-key。也支持同时填写多个api-key，如API_KEY="openai-key1,openai-key2,api2d-key3" 
 [API_KEY] 您既可以在config.py中修改api-key(s)，也可以在问题输入区输入临时的api-key(s)，然后回车键提交后即可生效。 
 [API_KEY] 您的 API_KEY 是: sk-a8Tvun8J66ZO*** API_KEY 导入成功 
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
[ENV_VAR] 尝试加载API_URL_REDIRECT，默认值：{} --> 修正值：{"https://api.openai.com/v1/chat/completions": "http://127.0.0.1:18080/v1/chat/completions"}
 [ENV_VAR] 成功读取环境变量API_URL_REDIRECT 
[ENV_VAR] 尝试加载LLM_MODEL，默认值：gpt-3.5-turbo --> 修正值：gpt-3.5-turbo-16k
 [ENV_VAR] 成功读取环境变量LLM_MODEL 
所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log, 请注意自我隐私保护哦！
查询代理的地理位置，返回的结果是{'error': True, 'reason': 'RateLimited', 'message': 'Visit https://ipapi.co/ratelimited/ for details'}
代理配置 socks5h://localhost:18890, 代理所在地：未知，IP查询频率受限
如果浏览器没有自动打开，请复制并转到以下URL：
	（亮色主题）: http://localhost:44015
	（暗色主题）: http://localhost:44015/?__theme=dark
正在执行一些模块的预热...
正在加载tokenizer，如果是第一次运行，可能需要一点时间下载参数
加载tokenizer完毕
正在加载tokenizer，如果是第一次运行，可能需要一点时间下载参数
加载tokenizer完毕
Running on local URL:  http://0.0.0.0:44015

To create a public link, set `share=True` in `launch()`.
[GFX1-]: glxtest: VA-API test failed: no supported VAAPI profile found.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
 gpt-3.5-turbo-16k : 0 : hello ..........
```

![image](https://github.com/binary-husky/gpt_academic/assets/11155854/a2326aa0-53cd-491a-9e0e-2c0e21f4ff20)
